site_name: Jean Nassar
site_url: https://jnassar.com
site_author: Jean Nassar
site_description: Senior Python and Robotics expert with 10+ years of interdisciplinary experience
repo_url: https://jnassar.com/assets/files/jnassar_resume.pdf
repo_name: Résumé

nav:
  - About:
      - About: "index.md"
      - Hire me: "hiring.md"
      - Testimonials: "testimonials.md"
  - Curriculum Vitae:
    - CV Overview: "cv.md"
    - Work Experience:
      - Work Overview: "cv/work.md"
      - Senior Software Engineer, Adimian: "cv/work/adimian.md"
      - Senior Python Developer, Yields.io: "cv/work/yields.md"
      - Industrial Automation Engineer, Kapernikov: "cv/work/kapernikov.md"
      - Data Scientist, Sentiance: "cv/work/sentiance.md"
      - Co-operative education experience: "cv/work/coop.md"
    - Projects:
        - Project Overview: "cv/projects.md"
        - Open Source projects: "cv/projects/open_source.md"
        - SPIRIT (Masters thesis): "cv/projects/spirit.md"
        - Yozakura: "cv/projects/yozakura.md"
        - Gestural Control of Robots: "cv/projects/myo.md"
        - Undergraduate projects: "cv/projects/undergrad.md"
    - Education:
        - Education Overview: "cv/education.md"
        - University of Waterloo: "cv/education/waterloo.md"
        - Kyoto University: "cv/education/kyoto.md"
    - Mentoring Experience: "cv/mentoring.md"
    - Skills: "cv/skills.md"
    - Tools and Technologies: "cv/tools.md"
  - Contact: "contact.md"

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/circle-light-transparent.png
  icon:
    repo: fontawesome/solid/file-pdf
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: teal
    - scheme: slate
      toggle:
          icon: material/weather-sunny
          name: Switch to light mode
      primary: indigo
      accent: teal
  font:
    text: Noto Sans
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
#    - content.action.edit
#    - content.action.view

extra_css:
  - assets/extra.css
extra_javascript:
  - assets/extra.js

plugins:
  - search
#  - awesome-pages
  - macros
  - obsidian-bridge:
      invalid_link_attributes:
        - 'style="color: red"'
  - i18n:
      default_language: en
      material_alternate: false
      languages:
        en:
          name: English
          build: true
          site_name: "Jean Nassar"
        fr:
          name: Français
          build: false
          site_name: "Jean Nassar"
          site_description: Expert en Python et en robotique
        nl:
          name: Nederlands
          build: false
          site_name: "Jean Nassar"
          site_description: Expert in Python en robotica
        ja:
          name: 日本語
          build: false
          site_name: "勝者神優"
          site_description: Pythonとロボットの専門家

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:contact@jnassar.com
      name: contact@jnassar.com
    - icon: fontawesome/solid/calendar
      link: https://cal.com/jnassar
      name: Book an appointment
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/masasin
      name: masasin
    - icon: fontawesome/brands/github-alt
      link: https://github.com/masasin
      name: masasin
    - icon: fontawesome/solid/code-pull-request
      link: https://github.com/masasin/masasin.github.io
      name: Contribute to this site
  urls:
    cv:
      pdf: (/assets/files/jnassar_resume.pdf){:target="_blank" rel="noopener"}
    edu:
      uwaterloo: (https://uwaterloo.ca/){:target="_blank" rel="noopener"}
      kyoto_u: (https://www.kyoto-u.ac.jp/en/){:target="_blank" rel="noopener"}
      matsuno: (http://www.mechatronics.me.kyoto-u.ac.jp/index.php?ml_lang=en){:target="_blank" rel="noopener"}
    work:
      adimian: (https://www.adimian.com/){:target="_blank" rel="noopener"}
      yields: (https://www.yields.io/){:target="_blank" rel="noopener"}
      kapernikov: (https://www.kapernikov.com/){:target="_blank" rel="noopener"}
      sentiance: (https://www.sentiance.com/){:target="_blank" rel="noopener"}
      starquip: (https://www.starquip.com/){:target="_blank" rel="noopener"}
      kqs: (https://kqbikes.com){:target="_blank" rel="noopener"}
      ims: (https://www.ims.tech/){:target="_blank" rel="noopener"}
      msam: (https://msam.uwaterloo.ca){:target="_blank" rel="noopener"}
      vrlab: (https://sites.aub.edu.lb/vrlab){:target="_blank" rel="noopener"}
      scs: (https://www.sierraconstructionsystems.com/){:target="_blank" rel="noopener"}
    projects:
      rtd: (https://readthedocs.org){:target="_blank" rel="noopener"}
      hri: (https://en.wikipedia.org/wiki/Human%E2%80%93robot_interaction){:target="_blank" rel="noopener"}
      latexipy: (https://github.com/masasin/latexipy){:target="_blank" rel="noopener"}
      pyrosbag: (https://github.com/masasin/pyrosbag){:target="_blank" rel="noopener"}
      resume: (https://github.com/masasin/resume){:target="_blank" rel="noopener"}
      aoc2021: (https://github.com/masasin/aoc2021){:target="_blank" rel="noopener"}
      aoc2022: (https://github.com/masasin/advent-of-code-2022){:target="_blank" rel="noopener"}
      dynamixel: (https://github.com/masasin/dynamixel){:target="_blank" rel="noopener"}
      myo_thalmic: (https://github.com/thalmiclabs){:target="_blank" rel="noopener"}
      spirit: (https://github.com/masasin/spirit){:target="_blank" rel="noopener"}
      spirit_wiki: (https://github.com/masasin/spirit/wiki){:target="_blank" rel="noopener"}
      spirit_components: (https://github.com/masasin/spirit/wiki/Components){:target="_blank" rel="noopener"}
      spirit_thesis: (https://github.com/masasin/spirit/releases/tag/v1.0){:target="_blank" rel="noopener"}
      yozakura: (https://github.com/kyoto-u-shinobi/yozakura_raspi){:target="_blank" rel="noopener"}
      yozakura_mbed: (https://github.com/kyoto-u-shinobi/yozakura_mbed){:target="_blank" rel="noopener"}
      yozakura_opstn: (https://github.com/kyoto-u-shinobi/yozakura_operator_station){:target="_blank" rel="noopener"}
      shinobi: (https://github.com/kyoto-u-shinobi){:target="_blank" rel="noopener"}
      robocup: (http://robocup.or.jp/){:target="_blank" rel="noopener"}
      rescue_league: (https://sites.google.com/site/robocupjorescuerobotleague/){:target="_blank" rel="noopener"}
      gilded_rose: (https://github.com/masasin/gilded-rose){:target="_blank" rel="noopener"}
      naca_airfoil_generator: (https://github.com/masasin/naca_airfoil_generator){:target="_blank" rel="noopener"}
      keep_talking_solver: (https://github.com/masasin/keep_talking_solver){:target="_blank" rel="noopener"}
      himawaripy: (https://github.com/masasin/himawaripy){:target="_blank" rel="noopener"}
    activities:
      konja: (https://www.uwkonja.com/about.html){:target="_blank" rel="noopener"}
      cube: (http://cube.uwaterloo.ca/index.php)
      cube_symposium: (http://cube.uwaterloo.ca/Symposium%202010%20web%20site/symp%202010.htm)
      uwclec: (https://uwclec.webs.com/){:target="_blank" rel="noopener"}
      ambassador: (https://uwaterloo.ca/engineering-student-ambassadors/){:target="_blank" rel="noopener"}
      shadow: (https://uwaterloo.ca/engineering-student-ambassadors/shadow-program){:target="_blank" rel="noopener"}
      japan_tent: (https://www.japantent.com/english.html){:target="_blank" rel="noopener"}
    mentoring:
      kotani: (https://aip.scitation.org/doi/pdf/10.1063/1.5028398?class=pdf){:target="_blank" rel="noopener"}
      codebar: (https://codebar.io/workshops/2547){:target="_blank" rel="noopener"}
    jobhunt:
      blue_card: (https://economy-employment.brussels/permit-blue-card){:target="_blank" rel="noopener"}
    social:
      linkedin: (https://www.linkedin.com/in/masasin){:target="_blank" rel="noopener"}
      github: (https://www.github.com/masasin){:target="_blank" rel="noopener"}
      email: (mailto:contact@jnassar.com)
      apprentus: (https://www.apprentus.com/in/jn.masasin){:target="_blank" rel="noopener"}
      cal: (#){data-cal-link="jnassar/call" data-cal-config='{"layout":"week_view"\}'}
  generator: false  # Support mkdocs material
copyright: |
  &copy; 2021 &ndash; 2023 <a href="https://github.com/masasin/" target="_blank" rel="noopener">Jean Nassar</a>.<br />
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC-BY-NC-SA 4.0 License</a>.
strict: false
