site_name: Jean Nassar
site_url: https://jnassar.com/
site_author: Jean Nassar
site_description: A Python and Robotics expert
theme:
  name: material
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: lime
    - scheme: slate
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
      primary: teal
      accent: lime
  font:
    text: Noto Serif
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
plugins:
  - search
  - awesome-pages
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/masasin
      name: masasin
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/masasin
      name: masasin
  generator: false
copyright: |
  &copy; 2021 &ndash; 2023 <a href="https://github.com/masasin/" target="_blank" rel="noopener">Jean Nassar</a>
