site_name: Jean Nassar
site_url: https://jnassar.com
site_author: Jean Nassar
site_description: Python and Robotics expert
#repo_url: https://github.com/masasin/masasin.github.io/
#edit_uri: edit/main/docs/

nav:
  - About me:
    - "index.md"
    - Curriculum Vitae: "cv/index.md"
    - Contact: "contact.md"
  - Curriculum Vitae:
    - "cv/index.md"
    - Work Experience:
      - "cv/work/index.md"
      - Senior Software Engineer, Adimian: "cv/work/adimian.md"
      - Senior Python Developer, Yields.io: "cv/work/yields.md"
      - Industrial Automation Engineer, Kapernikov: "cv/work/kapernikov.md"
      - Data Scientist, Sentiance: "cv/work/sentiance.md"
      - Co-operative education experience: "cv/work/coop.md"
    - Projects:
        - "cv/projects/index.md"
        - Open Source projects: "cv/projects/open_source.md"
        - SPIRIT (Masters thesis): "cv/projects/spirit.md"
        - Yozakura: "cv/projects/yozakura.md"
        - Gestural Control of Robots: "cv/projects/myo.md"
        - Undergraduate projects: "cv/projects/undergrad.md"
    - Education:
        - "cv/education/index.md"
        - University of Waterloo: "cv/education/waterloo.md"
        - Kyoto University: "cv/education/kyoto.md"
    - Skills: "cv/skills.md"
    - Teaching Experience: "cv/teaching.md"
    - Tools and Technologies: "cv/tools.md"
  - Contact: "contact.md"

theme:
  name: material
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: teal
    - scheme: slate
      toggle:
          icon: material/weather-sunny
          name: Switch to light mode
      primary: indigo
      accent: teal
  font:
    text: Noto Sans
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
#    - content.action.edit
#    - content.action.view
plugins:
  - search
#  - awesome-pages
  - i18n:
      default_language: en
      material_alternate: false
      languages:
        en:
          name: English
          build: true
          site_name: "Jean Nassar"
        fr:
          name: Français
          build: false
          site_name: "Jean Nassar"
          site_description: Expert en Python et en robotique
        nl:
          name: Nederlands
          build: false
          site_name: "Jean Nassar"
          site_description: Expert in Python en robotica
        ja:
          name: 日本語
          build: false
          site_name: "勝者神優"
          site_description: Pythonとロボットの専門家
      nav_translations:
        fr:
          About me: À propos de moi
          Curriculum Vitae: Curriculum Vitae
          Education: Éducation
          University of Waterloo: Université de Waterloo
          Kyoto University: Université de Kyoto
          Work experience: Expérience professionnelle
          Co-operative education experience: Expérience d'éducation coopérative
          Teaching experience: Expérience d'enseignement
          Projects: Projets
          Open Source Project Sampling: Projets open source
          SPIRIT (Masters thesis): SPIRIT (thèse de Master)
          Yozakura: Yozakura
          Gestural Control of Robots: Contrôle gestuel des robots
          Undergraduate projects: Projets de premier cycle
          Skills: Compétences
          Tools and Technologies: Outils et technologies
          Languages: Langues
        nl:
          About me: Over mij
          Curriculum Vitae: Curriculum Vitae
          Education: Opleiding
          University of Waterloo: Universiteit van Waterloo
          Kyoto University: Universiteit van Kyoto
          Work experience: Werkervaring
          Co-operative education experience: Coöperatieve onderwijservaring
          Teaching experience: Onderwijservaring
          Projects: Projecten
          Open Source Projects: Open source projecten
          SPIRIT (Masters thesis): SPIRIT (Masterthesis)
          Yozakura: Yozakura
          Gestural Control of Robots: Gebaarbesturing van robots
          Undergraduate projects: Bachelorprojecten
          Skills: Vaardigheden
          Tools and Technologies: Gereedschap en technologieën
          Languages: Talen
        ja:
          About me: 自己紹介
          Curriculum Vitae: 履歴書
          Education: 学歴
          University of Waterloo: ウォータールー大学
          Kyoto University: 京都大学
          Work experience: 職歴
          Co-operative education experience: 協同教育の経験
          Teaching experience: 教授経験
          Projects: プロジェクト一覧
          Open Source Project Sampling: オープンソースプロジェクト
          SPIRIT (Masters thesis): SPIRIT（修士論文）
          Yozakura: Yozakura
          Gestural Control of Robots: ジェスチャーによるロボット操作
          Undergraduate projects: 学部のプロジェクト
          Skills: スキル
          Tools and Technologies: ツールや技術
          Languages: 言語力

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:contact@jnassar.com
      name: contact@jnassar.com
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/masasin
      name: masasin
    - icon: fontawesome/brands/github-alt
      link: https://github.com/masasin
      name: masasin
    - icon: fontawesome/solid/code-pull-request
      link: https://gitlab.com/masasin/masasin.github.io
      name: Contribute to this site
  generator: false
copyright: |
  &copy; 2021 &ndash; 2023 <a href="https://github.com/masasin/" target="_blank" rel="noopener">Jean Nassar</a>
strict: true
