site_name: Jean Nassar
site_url: https://jnassar.com/
site_author: Jean Nassar
site_description: A Python and Robotics expert
theme:
  name: material
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: lime
    - scheme: slate
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
      primary: teal
      accent: lime
  font:
    text: Noto Serif
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
plugins:
  - search
  - awesome-pages
  - i18n:
      default_language: en
      material_alternate: false
      languages:
        en:
          name: English
          build: true
          site_name: "Jean Nassar"
        fr:
          name: Français
          build: false
          site_name: "Jean Nassar"
        nl:
          name: Nederlands
          build: false
          site_name: "Jean Nassar"
        ja:
          name: 日本語
          build: false
          site_name: "勝者神優"
      nav_translations:
        fr:
          About: Qui suis-je
        nl:
          About: Over mij
        ja:
          About: 自己紹介
          Portfolio: 職務経歴書
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:contact@jnassar.com
      name: contact@jnassar.com
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/masasin
      name: masasin
    - icon: fontawesome/brands/github-alt
      link: https://github.com/masasin
      name: masasin
    - icon: fontawesome/solid/code-pull-request
      link: https://github.com/masasin/masasin.github.io
      name: masasin.github.io
  generator: false
copyright: |
  &copy; 2021 &ndash; 2023 <a href="https://github.com/masasin/" target="_blank" rel="noopener">Jean Nassar</a>
strict: true