site_name: Jean Nassar
site_url: https://jnassar.com
site_author: Jean Nassar
site_description: Senior Python and Robotics expert with 10+ years of interdisciplinary experience
repo_url: https://jnassar.com/assets/files/jnassar_resume.pdf
repo_name: Résumé

nav:
  - Home: "index.md"
  - About:
      - About: "about.md"
      - Hire me: "hiring.md"
  - Curriculum Vitae:
    - CV Overview: "cv.md"
    - Work Experience:
      - Work Overview: "cv/work.md"
      - Senior Software Engineer, Adimian: "cv/work/adimian.md"
      - Senior Python Developer, Yields.io: "cv/work/yields.md"
      - Industrial Automation Engineer, Kapernikov: "cv/work/kapernikov.md"
      - Data Scientist, Sentiance: "cv/work/sentiance.md"
      - Co-operative education experience: "cv/work/coop.md"
    - Projects:
        - Project Overview: "cv/projects.md"
        - Open Source projects: "cv/projects/open_source.md"
        - SPIRIT (Masters thesis): "cv/projects/spirit.md"
        - Yozakura: "cv/projects/yozakura.md"
        - Gestural Control of Robots: "cv/projects/myo.md"
        - Undergraduate projects: "cv/projects/undergrad.md"
    - Education:
        - Education Overview: "cv/education.md"
        - University of Waterloo: "cv/education/waterloo.md"
        - Kyoto University: "cv/education/kyoto.md"
    - Mentoring Experience: "cv/mentoring.md"
    - Skills: "cv/skills.md"
    - Tools and Technologies: "cv/tools.md"
  - Contact: "contact.md"

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/circle-light-transparent.png
  icon:
    repo: fontawesome/solid/file-pdf
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: teal
    - scheme: slate
      toggle:
          icon: material/weather-sunny
          name: Switch to light mode
      primary: indigo
      accent: teal
  font:
    text: Noto Sans
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
#    - content.action.edit
#    - content.action.view
plugins:
  - search
#  - awesome-pages
  - macros
  - i18n:
      default_language: en
      material_alternate: false
      languages:
        en:
          name: English
          build: true
          site_name: "Jean Nassar"
        fr:
          name: Français
          build: false
          site_name: "Jean Nassar"
          site_description: Expert en Python et en robotique
        nl:
          name: Nederlands
          build: false
          site_name: "Jean Nassar"
          site_description: Expert in Python en robotica
        ja:
          name: 日本語
          build: false
          site_name: "勝者神優"
          site_description: Pythonとロボットの専門家
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: iso_date

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.progressbar
  - toc:
      permalink: true
  - markdown_captions
  - customblocks
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:contact@jnassar.com
      name: contact@jnassar.com
    - icon: fontawesome/solid/calendar
      link: https://cal.com/jnassar
      name: Book an appointment
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/masasin
      name: masasin
    - icon: fontawesome/brands/github-alt
      link: https://github.com/masasin
      name: masasin
    - icon: fontawesome/solid/code-pull-request
      link: https://github.com/masasin/masasin.github.io
      name: Contribute to this site
  urls:
    cv:
      pdf: (/assets/files/jnassar_resume.pdf){:target="_blank" rel="noopener"}
    edu:
      uwaterloo: (https://uwaterloo.ca/){:target="_blank" rel="noopener"}
      kyoto_u: (https://www.kyoto-u.ac.jp/en/){:target="_blank" rel="noopener"}
      matsuno: (http://www.mechatronics.me.kyoto-u.ac.jp/index.php?ml_lang=en){:target="_blank" rel="noopener"}
    work:
      adimian: (https://www.adimian.com/){:target="_blank" rel="noopener"}
      yields: (https://www.yields.io/){:target="_blank" rel="noopener"}
      kapernikov: (https://www.kapernikov.com/){:target="_blank" rel="noopener"}
      sentiance: (https://www.sentiance.com/){:target="_blank" rel="noopener"}
    jobhunt:
      blue_card: (https://economy-employment.brussels/permit-blue-card){:target="_blank" rel="noopener"}
    social:
      linkedin: (https://www.linkedin.com/in/masasin){:target="_blank" rel="noopener"}
      github: (https://www.github.com/masasin){:target="_blank" rel="noopener"}
      email: (mailto:contact@jnassar.com)
      apprentus: (https://www.apprentus.com/in/jn.masasin){:target="_blank" rel="noopener"}
      cal: (#){data-cal-link="jnassar/call" data-cal-config='{"layout":"week_view"\}'}
  generator: false
copyright: |
  &copy; 2021 &ndash; 2023 <a href="https://github.com/masasin/" target="_blank" rel="noopener">Jean Nassar</a>
strict: false
